networks:
    laravel-network:

services:
    nginx:
        build:
            context: ./docker
            dockerfile: nginx.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
                - USER=${USER:-laravel}
        restart: unless-stopped
        container_name: nginx
        ports:
            - 8000:8000
        volumes:
            - ./:/var/www/html
        depends_on:
            - php
        networks:
            - laravel-network

    php:
        build:
            context: ./docker
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
                - USER=${USER:-laravel}
        ports:
            - "9000"
        container_name: php
        volumes:
            - ./:/var/www/html
        networks:
            - laravel-network

    composer:
        build:
            context: ./docker
            dockerfile: composer.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
                - USER=${USER:-laravel}
        container_name: composer
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - php
        entrypoint: ["composer"]
        command: ["install", "--ignore-platform-reqs"]
        networks:
            - laravel-network
    artisan:
        build:
            context: ./docker
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
                - USER=${USER:-laravel}
        container_name: artisan
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - php
            - composer
            - nginx
        entrypoint: [ "sh", "-c" ]
        command: >
            '[ ! -f /var/www/html/.env ] && rm -rf /var/www/html/.env && cp /var/www/html/.env.example /var/www/html/.env; php /var/www/html/artisan key:generate; php /var/www/html/artisan "$$@" && php /var/www/html/artisan serve'
        networks:
            - laravel-network

    npm:
        image: node:18-alpine
        container_name: npm
        volumes:
            - ./:/var/www/html
        ports:
            - "3000:3000"
            - "3001:3001"
        working_dir: /var/www/html
        depends_on:
            - php
            - composer
        command: ["sh", "-c", "npm install && npm run dev"]
        networks:
            - laravel-network
