version: '3.8'
services:
    php:
        build:
            context: ./docker
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
                - USER=${USER:-laravel}
        container_name: php
        volumes:
            - .:/var/www/html
            - sqlite-data:/var/www/html/database
            - storage-data:/var/www/html/storage/app
        networks:
            - laravel-network

    artisan:
        build:
            context: ./docker
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
                - USER=${USER:-laravel}
        container_name: artisan
        volumes:
            - .:/var/www/html
            - sqlite-data:/var/www/html/database
            - storage-data:/var/www/html/storage/app
        working_dir: /var/www/html
        depends_on:
            - php
        entrypoint: ["sh", "-c"]
        command: |
            [ ! -f /var/www/html/.env ] && cp /var/www/html/.env.example /var/www/html/.env && php /var/www/html/artisan key:generate
            php /var/www/html/artisan serve --host=0.0.0.0 --port=8000
        ports:
            - "8000:8000"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        networks:
            - laravel-network

    nginx:
        build:
            context: ./docker
            dockerfile: nginx.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
                - USER=${USER:-laravel}
        restart: unless-stopped
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - sqlite-data:/var/www/html/database
            - storage-data:/var/www/html/storage/app
        depends_on:
            - php
        networks:
            - laravel-network

    npm:
        image: node:18-alpine
        container_name: npm
        volumes:
            - .:/var/www/html
            - storage-data:/var/www/html/storage/app
        ports:
            - "5173:5173"
        working_dir: /var/www/html
        depends_on:
            - artisan
        command: ["sh", "-c", "npm install && npm run dev"]
        networks:
            - laravel-network

    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        networks:
            - laravel-network

volumes:
    sqlite-data:
    storage-data:
    redis-data:

networks:
    laravel-network:
        driver: bridge
